-- Migration: Add Cookie Consent Tables
-- This is automatically generated by Prisma
-- You can run it manually if needed using: psql -d your_db -f this_file.sql

-- ─────────────────────────────────────────────────────────────
-- Create CookieConsent table
-- ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "cookie_consents" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "clientId" TEXT NOT NULL UNIQUE,
    "essential" BOOLEAN NOT NULL DEFAULT true,
    "analytics" BOOLEAN NOT NULL DEFAULT false,
    "marketing" BOOLEAN NOT NULL DEFAULT false,
    "ipAddress" TEXT,
    "userAgent" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMP(3) NOT NULL
);

-- Create indexes for better query performance
CREATE INDEX "cookie_consents_clientId_idx" ON "cookie_consents"("clientId");
CREATE INDEX "cookie_consents_createdAt_idx" ON "cookie_consents"("createdAt");

-- ─────────────────────────────────────────────────────────────
-- Create CookieConsentHistory table
-- ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "cookie_consent_history" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "clientId" TEXT NOT NULL,
    "essential" BOOLEAN,
    "analytics" BOOLEAN,
    "marketing" BOOLEAN,
    "action" TEXT NOT NULL,
    "ipAddress" TEXT,
    "userAgent" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for history queries
CREATE INDEX "cookie_consent_history_clientId_idx" ON "cookie_consent_history"("clientId");
CREATE INDEX "cookie_consent_history_createdAt_idx" ON "cookie_consent_history"("createdAt");

-- ─────────────────────────────────────────────────────────────
-- Create PrivacyPolicyVersion table
-- ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "privacy_policy_versions" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "version" TEXT NOT NULL UNIQUE,
    "content" TEXT NOT NULL,
    "published" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create index for version lookups
CREATE INDEX "privacy_policy_versions_version_idx" ON "privacy_policy_versions"("version");

-- ─────────────────────────────────────────────────────────────
-- Verify tables created
-- ─────────────────────────────────────────────────────────────

-- Run this to verify all tables exist:
-- \dt cookie* privacy*

-- Check table structure:
-- \d cookie_consents
-- \d cookie_consent_history
-- \d privacy_policy_versions
